### ISSUE TITLE
Rough Draft Feedback

### ISSUE THREAD

**Issue by Yuki-bach** [Yuki-bach/marketing#77]
## Comments
- Paper overall is reasonable, but there is a little too much repetition of the same basic information/ideas, methods, and results: Try to edit for conciseness if possible.
- Figure 1 is nice.

## Todo
- [x] Abstract should explain data to which methods are applied. Avoid “will” language: You are describing something you did, not will do.
- [x] Introduction should give more explicit examples of ML clustering used for marketing if possible.
- [x] Give link to Kaggle.
- [x] Section 3.1.1: Don’t use “I,” use “we,” since this is a paper with more than one author.
- [x] Figures 3-8 should all be in Results.
- [x] Figures 10-11 should be in Results.
- [x] Please avoid code screenshots if possible: Export results into a table. At least use light mode, not dark mode.
- [x] Methods and results are rather verbose, try to streamline presentation.
- [x] Clustering never seems to inform the supervised learning: Can you add cluster membership as a feature and see if that helps? 
- [x] Section 5.4 makes many claims that may be true, but don’t seem to be supported by the work or by any reference to outside literature: Can you try to provide additional support.
- [x] Don’t overstate success in your Conclusions: Be transparent about the limitations of your results.
- [x] General quality of writing: Writing uses a scholarly + neutral tone/style, language is concise, in-text citations are used correctly, and text is well-written overall. 8/12 (We always lose some points in this section).
